# Generated by Django 5.2.7 on 2025-11-14 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_house_created_at_alter_house_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='images',
        ),
    ]
