# Generated by Django 5.2.7 on 2025-10-18 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_is_student_user_is_teacher_alter_user_is_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_student',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_teacher',
        ),
    ]
