# Generated by Django 5.2.7 on 2025-11-14 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='rating',
            field=models.ForeignKey(blank=True, default=0.0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='house_ratings', to='app.rating'),
        ),
    ]
