# Generated by Django 5.2.7 on 2025-11-14 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_house_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
    ]
