# Generated by Django 5.2.7 on 2025-10-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arena',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='arena',
            name='rating',
        ),
    ]
