# Generated by Django 5.2.7 on 2025-10-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_arena_comments_remove_arena_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='arena_count',
            field=models.IntegerField(default=0),
        ),
    ]
